"""Shared wall-clock budget for real public CLI subprocess tests."""

_PRODUCT_MAX_PUBLIC_AGGREGATE_TIMEOUT_SECONDS = 270
_PUBLIC_CLI_TEST_CLEANUP_MARGIN_SECONDS = 30

PUBLIC_CLI_TEST_TIMEOUT_SECONDS = (
    _PRODUCT_MAX_PUBLIC_AGGREGATE_TIMEOUT_SECONDS
    + _PUBLIC_CLI_TEST_CLEANUP_MARGIN_SECONDS
)
